---
- hosts: master
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: update the hosts file
      template: src=templates/hosts.j2 dest=/etc/hosts
    - name: adds mesosphere apt-key
      apt_key: keyserver=keyserver.ubuntu.com id=E56151BF
    - name: install the mesosphere repo 
      apt_repository: repo='deb http://repos.mesosphere.com/ubuntu trusty main' state=present
    - name: install java 8 oracle ppa
      apt_repository: repo="ppa:webupd8team/java" state=present

    - name: Accept Java 8 License
      sudo: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install mesosphere packages
      apt: name={{item}} state=latest update_cache=yes force=yes
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
        - mesos
        - marathon
        - chronos 
    - name: Installs docker
      apt: name=docker.io state=present 
    - name: configure zookeeper id
      copy: content=1 dest=/etc/zookeeper/conf/myid 
    - name: configure mesos to use containers
      shell: echo 'docker,mesos' | sudo tee /etc/mesos-slave/containerizers
    - name: start up zookeeper
      service: name=zookeeper state=started enabled=yes
    - name: start up the mesos master
      service: name=mesos-master state=started enabled=yes
    - name: make sure mesos-slave is running
      service: name=mesos-slave state=started enabled=yes
    - name: make sure marathon is running
      service: name=marathon state=started enabled=yes
    - name: make sure chronos is running
      service: name=chronos state=started enabled=yes
    - name: start docker
      service: name=docker state=started enabled=yes
    - name: build mesos-dns
      shell: sudo -u vagrant sh /vagrant/mesos-dns/installdns.sh
    - name: update the rsyslog config
      template: src=templates/syslog_mesos.conf.j2 dest=/etc/rsyslog.d/mesos.conf
    - name: restart rsyslog
      service: name=rsyslog state=restarted enabled=yes

- hosts: nodes
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: update the hosts file
      template: src=templates/hosts.j2 dest=/etc/hosts
    - name: adds mesosphere apt-key
      apt_key: keyserver=keyserver.ubuntu.com id=E56151BF
    - name: install the mesosphere repo 
      apt_repository: repo='deb http://repos.mesosphere.com/ubuntu trusty main' state=present 
    - name: Install mesos
      apt: name=mesos state=present update_cache=yes
    - name: Installs docker
      apt: name=docker.io state=present 
    - name: configure zookeeper id
      copy: content=1 dest=/etc/zookeeper/conf/myid 
    - name: configure mesos to use containers
      shell: echo 'docker,mesos' | sudo tee /etc/mesos-slave/containerizers
    - name: set the zookeeper master
      shell: sed -i -e 's/localhost/192.168.33.10/g' /etc/mesos/zk
    - name: build mesos-dns
      shell: sudo -u vagrant sh /vagrant/mesos-dns/installdns.sh
    - name: update the rsyslog config
      template: src=templates/syslog_mesos.conf.j2 dest=/etc/rsyslog.d/mesos.conf
    - name: restart rsyslog
      service: name=rsyslog state=restarted enabled=yes
    - name: make sure mesos-slave is running
      service: name=mesos-slave state=started enabled=yes
    - name: start docker
      service: name=docker state=started enabled=yes

